### ISSUE TITLE
Mark this repo INACTIVE / archive

### ISSUE THREAD

**Issue by jdolitsky** [opencontainers/foundation#1]
The description is:

```
Foundation Governance and Legal Documents
```

But there are no documents in the repo since it was created.

Can we mark this repo INACTIVE by prefixing the description with [INACTIVE] similar to these repos?

- https://github.com/opencontainers/runc.io
- https://github.com/opencontainers/web

And archiving it in GitHub settings?

**Comment by amye** [comment]
Archiving, if we need it again, we'll undo it.
